In [1]:
import pandas as pd
import os

In [2]:
predictions = None

for file in sorted(os.listdir()):
    if os.path.isdir(file) and file != "old":
       df = pd.read_csv(os.path.join(file, "predictions.csv"), index_col=0)
       model_index = file.split()[0]
       if predictions is None:
           predictions = df
           predictions.rename(columns={"y_pred": f"model {model_index}"}, inplace=True)
           continue
       predictions[f"model {model_index}"] = df.y_pred

predictions.to_csv("predictions.csv")
predictions.head()

,target_organism,train,curated_smiles,pIC50,model 01,model 02,model 03,model 04,model 05,model 06
3218,Salmonella enterica subsp. enterica serovar Ty...,False,CCCCCc1[nH]c(=N)n(CC(=O)Nc2ccc(C)cc2)c1-c1cccc...,1.501689,1.703981,1.680605,1.610187,1.560952,1.861674,1.774664
9448,Staphylococcus aureus,False,Oc1cc(Cl)ccc1Oc1ccc(Cl)cc1Cl,1.966172,2.705194,1.918393,2.880857,2.144288,2.710427,2.513604
2491,Raoultella planticola,False,CO[C@@]12C(=COC(N)=O)c3c(O)c(N)c(C)c(O)c3N1C[C...,2.958607,3.283466,3.081834,3.353389,3.258607,3.128974,2.130078
319,Salmonella enterica subsp. enterica serovar Ty...,False,N=c1[nH]cc(-c2ccc(Cl)cc2)n1C1CCCCC1,1.478862,1.668464,1.713783,1.553982,1.632399,1.491442,1.727018
508,Staphylococcus aureus,False,CC(C)[C@@H]1CC[C@@H](C)C[C@H]1OC(=O)NCCCCCCCc1...,1.271646,1.409023,1.390620,1.513311,1.866465,1.538545,1.418425

In [4]:
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

metrics = pd.DataFrame(index=["R2", "MAE", "RMSE"])
for column in predictions.columns[-6:]:
    metrics[column] = [
        r2_score(predictions.pIC50, predictions[column]),
        mean_absolute_error(predictions.pIC50, predictions[column]),
        mean_squared_error(predictions.pIC50, predictions[column])**0.5
    ]

metrics.T.round(3)

             R2    MAE   RMSE
model 01  0.610  0.321  0.438
model 02  0.538  0.365  0.477
model 03  0.573  0.331  0.459
model 04  0.532  0.361  0.480
model 05  0.491  0.374  0.501
model 06  0.472  0.375  0.510